export const countries = Object.freeze([
  {
    id: `afg_4`,
    short_code: 'af',
    long_code: 'afg',
    name: 'Afghanistan',
  },
  {
    id: `alb_8`,
    short_code: 'al',
    long_code: 'alb',
    name: 'Albania',
  },
  {
    id: `dza_12`,
    short_code: 'dz',
    long_code: 'dza',
    name: 'Algeria',
  },
  {
    id: `and_20`,
    short_code: 'ad',
    long_code: 'and',
    name: 'Andorra',
  },
  {
    id: `ago_24`,
    short_code: 'ao',
    long_code: 'ago',
    name: 'Angola',
  },
  {
    id: `atg_28`,
    short_code: 'ag',
    long_code: 'atg',
    name: 'Antigua and Barbuda',
  },
  {
    id: `arg_32`,
    short_code: 'ar',
    long_code: 'arg',
    name: 'Argentina',
  },
  {
    id: `arm_51`,
    short_code: 'am',
    long_code: 'arm',
    name: 'Armenia',
  },
  {
    id: `aus_36`,
    short_code: 'au',
    long_code: 'aus',
    name: 'Australia',
  },
  {
    id: `aut_40`,
    short_code: 'at',
    long_code: 'aut',
    name: 'Austria',
  },
  {
    id: `aze_31`,
    short_code: 'az',
    long_code: 'aze',
    name: 'Azerbaijan',
  },
  {
    id: `bhs_44`,
    short_code: 'bs',
    long_code: 'bhs',
    name: 'Bahamas',
  },
  {
    id: `bhr_48`,
    short_code: 'bh',
    long_code: 'bhr',
    name: 'Bahrain',
  },
  {
    id: `bgd_50`,
    short_code: 'bd',
    long_code: 'bgd',
    name: 'Bangladesh',
  },
  {
    id: `brb_52`,
    short_code: 'bb',
    long_code: 'brb',
    name: 'Barbados',
  },
  {
    id: `blr_112`,
    short_code: 'by',
    long_code: 'blr',
    name: 'Belarus',
  },
  {
    id: `bel_56`,
    short_code: 'be',
    long_code: 'bel',
    name: 'Belgium',
  },
  {
    id: `blz_84`,
    short_code: 'bz',
    long_code: 'blz',
    name: 'Belize',
  },
  {
    id: `ben_204`,
    short_code: 'bj',
    long_code: 'ben',
    name: 'Benin',
  },
  {
    id: `btn_64`,
    short_code: 'bt',
    long_code: 'btn',
    name: 'Bhutan',
  },
  {
    id: `bol_68`,
    short_code: 'bo',
    long_code: 'bol',
    name: 'Bolivia, Plurinational State of',
  },
  {
    id: `bih_70`,
    short_code: 'ba',
    long_code: 'bih',
    name: 'Bosnia and Herzegovina',
  },
  {
    id: `bwa_72`,
    short_code: 'bw',
    long_code: 'bwa',
    name: 'Botswana',
  },
  {
    id: `bra_76`,
    short_code: 'br',
    long_code: 'bra',
    name: 'Brazil',
  },
  {
    id: `brn_96`,
    short_code: 'bn',
    long_code: 'brn',
    name: 'Brunei Darussalam',
  },
  {
    id: `bgr_100`,
    short_code: 'bg',
    long_code: 'bgr',
    name: 'Bulgaria',
  },
  {
    id: `bfa_854`,
    short_code: 'bf',
    long_code: 'bfa',
    name: 'Burkina Faso',
  },
  {
    id: `bdi_108`,
    short_code: 'bi',
    long_code: 'bdi',
    name: 'Burundi',
  },
  {
    id: `cpv_132`,
    short_code: 'cv',
    long_code: 'cpv',
    name: 'Cabo Verde',
  },
  {
    id: `khm_116`,
    short_code: 'kh',
    long_code: 'khm',
    name: 'Cambodia',
  },
  {
    id: `cmr_120`,
    short_code: 'cm',
    long_code: 'cmr',
    name: 'Cameroon',
  },
  {
    id: `can_124`,
    short_code: 'ca',
    long_code: 'can',
    name: 'Canada',
  },
  {
    id: `caf_140`,
    short_code: 'cf',
    long_code: 'caf',
    name: 'Central African Republic',
  },
  {
    id: `tcd_148`,
    short_code: 'td',
    long_code: 'tcd',
    name: 'Chad',
  },
  {
    id: `chl_152`,
    short_code: 'cl',
    long_code: 'chl',
    name: 'Chile',
  },
  {
    id: `chn_156`,
    short_code: 'cn',
    long_code: 'chn',
    name: 'China',
  },
  {
    id: `col_170`,
    short_code: 'co',
    long_code: 'col',
    name: 'Colombia',
  },
  {
    id: `com_174`,
    short_code: 'km',
    long_code: 'com',
    name: 'Comoros',
  },
  {
    id: `cog_178`,
    short_code: 'cg',
    long_code: 'cog',
    name: 'Congo',
  },
  {
    id: `cod_180`,
    short_code: 'cd',
    long_code: 'cod',
    name: 'Congo, Democratic Republic of the',
  },
  {
    id: `cri_188`,
    short_code: 'cr',
    long_code: 'cri',
    name: 'Costa Rica',
  },
  {
    id: `civ_384`,
    short_code: 'ci',
    long_code: 'civ',
    name: "Côte d'Ivoire",
  },
  {
    id: `hrv_191`,
    short_code: 'hr',
    long_code: 'hrv',
    name: 'Croatia',
  },
  {
    id: `cub_192`,
    short_code: 'cu',
    long_code: 'cub',
    name: 'Cuba',
  },
  {
    id: `cyp_196`,
    short_code: 'cy',
    long_code: 'cyp',
    name: 'Cyprus',
  },
  {
    id: `cze_203`,
    short_code: 'cz',
    long_code: 'cze',
    name: 'Czechia',
  },
  {
    id: `dnk_208`,
    short_code: 'dk',
    long_code: 'dnk',
    name: 'Denmark',
  },
  {
    id: `dji_262`,
    short_code: 'dj',
    long_code: 'dji',
    name: 'Djibouti',
  },
  {
    id: `dma_212`,
    short_code: 'dm',
    long_code: 'dma',
    name: 'Dominica',
  },
  {
    id: `dom_214`,
    short_code: 'do',
    long_code: 'dom',
    name: 'Dominican Republic',
  },
  {
    id: `ecu_218`,
    short_code: 'ec',
    long_code: 'ecu',
    name: 'Ecuador',
  },
  {
    id: `egy_818`,
    short_code: 'eg',
    long_code: 'egy',
    name: 'Egypt',
  },
  {
    id: `slv_222`,
    short_code: 'sv',
    long_code: 'slv',
    name: 'El Salvador',
  },
  {
    id: `gnq_226`,
    short_code: 'gq',
    long_code: 'gnq',
    name: 'Equatorial Guinea',
  },
  {
    id: `eri_232`,
    short_code: 'er',
    long_code: 'eri',
    name: 'Eritrea',
  },
  {
    id: `est_233`,
    short_code: 'ee',
    long_code: 'est',
    name: 'Estonia',
  },
  {
    id: `swz_748`,
    short_code: 'sz',
    long_code: 'swz',
    name: 'Eswatini',
  },
  {
    id: `eth_231`,
    short_code: 'et',
    long_code: 'eth',
    name: 'Ethiopia',
  },
  {
    id: `fji_242`,
    short_code: 'fj',
    long_code: 'fji',
    name: 'Fiji',
  },
  {
    id: `fin_246`,
    short_code: 'fi',
    long_code: 'fin',
    name: 'Finland',
  },
  {
    id: `fra_250`,
    short_code: 'fr',
    long_code: 'fra',
    name: 'France',
  },
  {
    id: `gab_266`,
    short_code: 'ga',
    long_code: 'gab',
    name: 'Gabon',
  },
  {
    id: `gmb_270`,
    short_code: 'gm',
    long_code: 'gmb',
    name: 'Gambia',
  },
  {
    id: `geo_268`,
    short_code: 'ge',
    long_code: 'geo',
    name: 'Georgia',
  },
  {
    id: `deu_276`,
    short_code: 'de',
    long_code: 'deu',
    name: 'Germany',
  },
  {
    id: `gha_288`,
    short_code: 'gh',
    long_code: 'gha',
    name: 'Ghana',
  },
  {
    id: `grc_300`,
    short_code: 'gr',
    long_code: 'grc',
    name: 'Greece',
  },
  {
    id: `grd_308`,
    short_code: 'gd',
    long_code: 'grd',
    name: 'Grenada',
  },
  {
    id: `gtm_320`,
    short_code: 'gt',
    long_code: 'gtm',
    name: 'Guatemala',
  },
  {
    id: `gin_324`,
    short_code: 'gn',
    long_code: 'gin',
    name: 'Guinea',
  },
  {
    id: `gnb_624`,
    short_code: 'gw',
    long_code: 'gnb',
    name: 'Guinea-Bissau',
  },
  {
    id: `guy_328`,
    short_code: 'gy',
    long_code: 'guy',
    name: 'Guyana',
  },
  {
    id: `hti_332`,
    short_code: 'ht',
    long_code: 'hti',
    name: 'Haiti',
  },
  {
    id: `hnd_340`,
    short_code: 'hn',
    long_code: 'hnd',
    name: 'Honduras',
  },
  {
    id: `hun_348`,
    short_code: 'hu',
    long_code: 'hun',
    name: 'Hungary',
  },
  {
    id: `isl_352`,
    short_code: 'is',
    long_code: 'isl',
    name: 'Iceland',
  },
  {
    id: `ind_356`,
    short_code: 'in',
    long_code: 'ind',
    name: 'India',
  },
  {
    id: `idn_360`,
    short_code: 'id',
    long_code: 'idn',
    name: 'Indonesia',
  },
  {
    id: `irn_364`,
    short_code: 'ir',
    long_code: 'irn',
    name: 'Iran, Islamic Republic of',
  },
  {
    id: `irq_368`,
    short_code: 'iq',
    long_code: 'irq',
    name: 'Iraq',
  },
  {
    id: `irl_372`,
    short_code: 'ie',
    long_code: 'irl',
    name: 'Ireland',
  },
  {
    id: `isr_376`,
    short_code: 'il',
    long_code: 'isr',
    name: 'Israel',
  },
  {
    id: `ita_380`,
    short_code: 'it',
    long_code: 'ita',
    name: 'Italy',
  },
  {
    id: `jam_388`,
    short_code: 'jm',
    long_code: 'jam',
    name: 'Jamaica',
  },
  {
    id: `jpn_392`,
    short_code: 'jp',
    long_code: 'jpn',
    name: 'Japan',
  },
  {
    id: `jor_400`,
    short_code: 'jo',
    long_code: 'jor',
    name: 'Jordan',
  },
  {
    id: `kaz_398`,
    short_code: 'kz',
    long_code: 'kaz',
    name: 'Kazakhstan',
  },
  {
    id: `ken_404`,
    short_code: 'ke',
    long_code: 'ken',
    name: 'Kenya',
  },
  {
    id: `kir_296`,
    short_code: 'ki',
    long_code: 'kir',
    name: 'Kiribati',
  },
  {
    id: `prk_408`,
    short_code: 'kp',
    long_code: 'prk',
    name: "Korea, Democratic People's Republic of",
  },
  {
    id: `kor_410`,
    short_code: 'kr',
    long_code: 'kor',
    name: 'Korea, Republic of',
  },
  {
    id: `kwt_414`,
    short_code: 'kw',
    long_code: 'kwt',
    name: 'Kuwait',
  },
  {
    id: `kgz_417`,
    short_code: 'kg',
    long_code: 'kgz',
    name: 'Kyrgyzstan',
  },
  {
    id: `lao_418`,
    short_code: 'la',
    long_code: 'lao',
    name: "Lao People's Democratic Republic",
  },
  {
    id: `lva_428`,
    short_code: 'lv',
    long_code: 'lva',
    name: 'Latvia',
  },
  {
    id: `lbn_422`,
    short_code: 'lb',
    long_code: 'lbn',
    name: 'Lebanon',
  },
  {
    id: `lso_426`,
    short_code: 'ls',
    long_code: 'lso',
    name: 'Lesotho',
  },
  {
    id: `lbr_430`,
    short_code: 'lr',
    long_code: 'lbr',
    name: 'Liberia',
  },
  {
    id: `lby_434`,
    short_code: 'ly',
    long_code: 'lby',
    name: 'Libya',
  },
  {
    id: `lie_438`,
    short_code: 'li',
    long_code: 'lie',
    name: 'Liechtenstein',
  },
  {
    id: `ltu_440`,
    short_code: 'lt',
    long_code: 'ltu',
    name: 'Lithuania',
  },
  {
    id: `lux_442`,
    short_code: 'lu',
    long_code: 'lux',
    name: 'Luxembourg',
  },
  {
    id: `mdg_450`,
    short_code: 'mg',
    long_code: 'mdg',
    name: 'Madagascar',
  },
  {
    id: `mwi_454`,
    short_code: 'mw',
    long_code: 'mwi',
    name: 'Malawi',
  },
  {
    id: `mys_458`,
    short_code: 'my',
    long_code: 'mys',
    name: 'Malaysia',
  },
  {
    id: `mdv_462`,
    short_code: 'mv',
    long_code: 'mdv',
    name: 'Maldives',
  },
  {
    id: `mli_466`,
    short_code: 'ml',
    long_code: 'mli',
    name: 'Mali',
  },
  {
    id: `mlt_470`,
    short_code: 'mt',
    long_code: 'mlt',
    name: 'Malta',
  },
  {
    id: `mhl_584`,
    short_code: 'mh',
    long_code: 'mhl',
    name: 'Marshall Islands',
  },
  {
    id: `mrt_478`,
    short_code: 'mr',
    long_code: 'mrt',
    name: 'Mauritania',
  },
  {
    id: `mus_480`,
    short_code: 'mu',
    long_code: 'mus',
    name: 'Mauritius',
  },
  {
    id: `mex_484`,
    short_code: 'mx',
    long_code: 'mex',
    name: 'Mexico',
  },
  {
    id: `fsm_583`,
    short_code: 'fm',
    long_code: 'fsm',
    name: 'Micronesia, Federated States of',
  },
  {
    id: `mda_498`,
    short_code: 'md',
    long_code: 'mda',
    name: 'Moldova, Republic of',
  },
  {
    id: `mco_492`,
    short_code: 'mc',
    long_code: 'mco',
    name: 'Monaco',
  },
  {
    id: `mng_496`,
    short_code: 'mn',
    long_code: 'mng',
    name: 'Mongolia',
  },
  {
    id: `mne_499`,
    short_code: 'me',
    long_code: 'mne',
    name: 'Montenegro',
  },
  {
    id: `mar_504`,
    short_code: 'ma',
    long_code: 'mar',
    name: 'Morocco',
  },
  {
    id: `moz_508`,
    short_code: 'mz',
    long_code: 'moz',
    name: 'Mozambique',
  },
  {
    id: `mmr_104`,
    short_code: 'mm',
    long_code: 'mmr',
    name: 'Myanmar',
  },
  {
    id: `nam_516`,
    short_code: 'na',
    long_code: 'nam',
    name: 'Namibia',
  },
  {
    id: `nru_520`,
    short_code: 'nr',
    long_code: 'nru',
    name: 'Nauru',
  },
  {
    id: `npl_524`,
    short_code: 'np',
    long_code: 'npl',
    name: 'Nepal',
  },
  {
    id: `nld_528`,
    short_code: 'nl',
    long_code: 'nld',
    name: 'Netherlands',
  },
  {
    id: `nzl_554`,
    short_code: 'nz',
    long_code: 'nzl',
    name: 'New Zealand',
  },
  {
    id: `nic_558`,
    short_code: 'ni',
    long_code: 'nic',
    name: 'Nicaragua',
  },
  {
    id: `ner_562`,
    short_code: 'ne',
    long_code: 'ner',
    name: 'Niger',
  },
  {
    id: `nga_566`,
    short_code: 'ng',
    long_code: 'nga',
    name: 'Nigeria',
  },
  {
    id: `mkd_807`,
    short_code: 'mk',
    long_code: 'mkd',
    name: 'North Macedonia',
  },
  {
    id: `nor_578`,
    short_code: 'no',
    long_code: 'nor',
    name: 'Norway',
  },
  {
    id: `omn_512`,
    short_code: 'om',
    long_code: 'omn',
    name: 'Oman',
  },
  {
    id: `pak_586`,
    short_code: 'pk',
    long_code: 'pak',
    name: 'Pakistan',
  },
  {
    id: `plw_585`,
    short_code: 'pw',
    long_code: 'plw',
    name: 'Palau',
  },
  {
    id: `pan_591`,
    short_code: 'pa',
    long_code: 'pan',
    name: 'Panama',
  },
  {
    id: `png_598`,
    short_code: 'pg',
    long_code: 'png',
    name: 'Papua New Guinea',
  },
  {
    id: `pry_600`,
    short_code: 'py',
    long_code: 'pry',
    name: 'Paraguay',
  },
  {
    id: `per_604`,
    short_code: 'pe',
    long_code: 'per',
    name: 'Peru',
  },
  {
    id: `phl_608`,
    short_code: 'ph',
    long_code: 'phl',
    name: 'Philippines',
  },
  {
    id: `pol_616`,
    short_code: 'pl',
    long_code: 'pol',
    name: 'Poland',
  },
  {
    id: `prt_620`,
    short_code: 'pt',
    long_code: 'prt',
    name: 'Portugal',
  },
  {
    id: `qat_634`,
    short_code: 'qa',
    long_code: 'qat',
    name: 'Qatar',
  },
  {
    id: `rou_642`,
    short_code: 'ro',
    long_code: 'rou',
    name: 'Romania',
  },
  {
    id: `rus_643`,
    short_code: 'ru',
    long_code: 'rus',
    name: 'Russian Federation',
  },
  {
    id: `rwa_646`,
    short_code: 'rw',
    long_code: 'rwa',
    name: 'Rwanda',
  },
  {
    id: `kna_659`,
    short_code: 'kn',
    long_code: 'kna',
    name: 'Saint Kitts and Nevis',
  },
  {
    id: `lca_662`,
    short_code: 'lc',
    long_code: 'lca',
    name: 'Saint Lucia',
  },
  {
    id: `vct_670`,
    short_code: 'vc',
    long_code: 'vct',
    name: 'Saint Vincent and the Grenadines',
  },
  {
    id: `wsm_882`,
    short_code: 'ws',
    long_code: 'wsm',
    name: 'Samoa',
  },
  {
    id: `smr_674`,
    short_code: 'sm',
    long_code: 'smr',
    name: 'San Marino',
  },
  {
    id: `stp_678`,
    short_code: 'st',
    long_code: 'stp',
    name: 'Sao Tome and Principe',
  },
  {
    id: `sau_682`,
    short_code: 'sa',
    long_code: 'sau',
    name: 'Saudi Arabia',
  },
  {
    id: `sen_686`,
    short_code: 'sn',
    long_code: 'sen',
    name: 'Senegal',
  },
  {
    id: `srb_688`,
    short_code: 'rs',
    long_code: 'srb',
    name: 'Serbia',
  },
  {
    id: `syc_690`,
    short_code: 'sc',
    long_code: 'syc',
    name: 'Seychelles',
  },
  {
    id: `sle_694`,
    short_code: 'sl',
    long_code: 'sle',
    name: 'Sierra Leone',
  },
  {
    id: `sgp_702`,
    short_code: 'sg',
    long_code: 'sgp',
    name: 'Singapore',
  },
  {
    id: `svk_703`,
    short_code: 'sk',
    long_code: 'svk',
    name: 'Slovakia',
  },
  {
    id: `svn_705`,
    short_code: 'si',
    long_code: 'svn',
    name: 'Slovenia',
  },
  {
    id: `slb_90`,
    short_code: 'sb',
    long_code: 'slb',
    name: 'Solomon Islands',
  },
  {
    id: `som_706`,
    short_code: 'so',
    long_code: 'som',
    name: 'Somalia',
  },
  {
    id: `zaf_710`,
    short_code: 'za',
    long_code: 'zaf',
    name: 'South Africa',
  },
  {
    id: `ssd_728`,
    short_code: 'ss',
    long_code: 'ssd',
    name: 'South Sudan',
  },
  {
    id: `esp_724`,
    short_code: 'es',
    long_code: 'esp',
    name: 'Spain',
  },
  {
    id: `lka_144`,
    short_code: 'lk',
    long_code: 'lka',
    name: 'Sri Lanka',
  },
  {
    id: `sdn_729`,
    short_code: 'sd',
    long_code: 'sdn',
    name: 'Sudan',
  },
  {
    id: `sur_740`,
    short_code: 'sr',
    long_code: 'sur',
    name: 'Suriname',
  },
  {
    id: `swe_752`,
    short_code: 'se',
    long_code: 'swe',
    name: 'Sweden',
  },
  {
    id: `che_756`,
    short_code: 'ch',
    long_code: 'che',
    name: 'Switzerland',
  },
  {
    id: `syr_760`,
    short_code: 'sy',
    long_code: 'syr',
    name: 'Syrian Arab Republic',
  },
  {
    id: `tjk_762`,
    short_code: 'tj',
    long_code: 'tjk',
    name: 'Tajikistan',
  },
  {
    id: `tza_834`,
    short_code: 'tz',
    long_code: 'tza',
    name: 'Tanzania, United Republic of',
  },
  {
    id: `tha_764`,
    short_code: 'th',
    long_code: 'tha',
    name: 'Thailand',
  },
  {
    id: `tls_626`,
    short_code: 'tl',
    long_code: 'tls',
    name: 'Timor-Leste',
  },
  {
    id: `tgo_768`,
    short_code: 'tg',
    long_code: 'tgo',
    name: 'Togo',
  },
  {
    id: `ton_776`,
    short_code: 'to',
    long_code: 'ton',
    name: 'Tonga',
  },
  {
    id: `tto_780`,
    short_code: 'tt',
    long_code: 'tto',
    name: 'Trinidad and Tobago',
  },
  {
    id: `tun_788`,
    short_code: 'tn',
    long_code: 'tun',
    name: 'Tunisia',
  },
  {
    id: `tur_792`,
    short_code: 'tr',
    long_code: 'tur',
    name: 'Türkiye',
  },
  {
    id: `tkm_795`,
    short_code: 'tm',
    long_code: 'tkm',
    name: 'Turkmenistan',
  },
  {
    id: `tuv_798`,
    short_code: 'tv',
    long_code: 'tuv',
    name: 'Tuvalu',
  },
  {
    id: `uga_800`,
    short_code: 'ug',
    long_code: 'uga',
    name: 'Uganda',
  },
  {
    id: `ukr_804`,
    short_code: 'ua',
    long_code: 'ukr',
    name: 'Ukraine',
  },
  {
    id: `are_784`,
    short_code: 'ae',
    long_code: 'are',
    name: 'United Arab Emirates',
  },
  {
    id: `gbr_826`,
    short_code: 'gb',
    long_code: 'gbr',
    name: 'United Kingdom of Great Britain and Northern Ireland',
  },
  {
    id: `usa_840`,
    short_code: 'us',
    long_code: 'usa',
    name: 'United States of America',
  },
  {
    id: `ury_858`,
    short_code: 'uy',
    long_code: 'ury',
    name: 'Uruguay',
  },
  {
    id: `uzb_860`,
    short_code: 'uz',
    long_code: 'uzb',
    name: 'Uzbekistan',
  },
  {
    id: `vut_548`,
    short_code: 'vu',
    long_code: 'vut',
    name: 'Vanuatu',
  },
  {
    id: `ven_862`,
    short_code: 've',
    long_code: 'ven',
    name: 'Venezuela, Bolivarian Republic of',
  },
  {
    id: `vnm_704`,
    short_code: 'vn',
    long_code: 'vnm',
    name: 'Viet Nam',
  },
  {
    id: `yem_887`,
    short_code: 'ye',
    long_code: 'yem',
    name: 'Yemen',
  },
  {
    id: `zmb_894`,
    short_code: 'zm',
    long_code: 'zmb',
    name: 'Zambia',
  },
  {
    id: `zwe_716`,
    short_code: 'zw',
    long_code: 'zwe',
    name: 'Zimbabwe',
  },
]);
